const N={force:"A — FORCE",toss:"B — TOSS ENGINE",speed:"C — SPEED TRANSFER",armor:"D — ARMOR",cheer:"CHEER",recovery:"RECOVERY"},DESC={force:"Força absoluta",toss:"Tripla extensão + dip/drive",speed:"Potência e velocidade",armor:"Core + overhead + prehab",cheer:"Stunts / skills",recovery:"Recuperação"};
const PH=[["Fase 1","Base & padrão vertical"],["Fase 2","Força máxima & tripla extensão"],["Deload","Semana 8 — deload técnico"],["Fase 3","Potência & transferência"],["Fase 4","Pico de performance"],["Testes","Semana 16 — deload & testes"]];
const KEY="arthurCheerV5";let S=JSON.parse(localStorage.getItem(KEY)||"null")||{week:1,offset:0,schedule:{},days:{},scores:{}};const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,pi=w=>w<=4?0:w<=7?1:w===8?2:w<=12?3:w<=15?4:5;
function dates(){let d=new Date(),w=d.getDay();d.setDate(d.getDate()+(w===0?-6:1-w)+S.offset*7);d.setHours(0,0,0,0);return Array.from({length:7},(_,i)=>{let x=new Date(d);x.setDate(x.getDate()+i);return x})}
function seed(ds){["force","toss","speed","cheer","recovery","cheer","cheer"].forEach((t,i)=>{let k=iso(ds[i]);if(!(k in S.schedule))S.schedule[k]=[t]});save()}
function todayData(){let k=iso(new Date());return S.days[k]||(S.days[k]={done:[]})}
function workout(t){let p=pi(S.week);
if(t==="cheer")return [["CHEER — Transferência","Cue: EMPURRA O CHÃO E CRESCE. DOWN → UP.","Treino específico"],["Toss Quality","Registre o Toss Quality Score depois do treino.","2 min"]];
if(t==="recovery")return [["Recuperação","Descanso ou cardio muito leve.","20–30 min"],["Mobilidade","Tornozelo, quadril, T-spine e ombros.","10–15 min"]];
if(t==="armor")return [["Cupie / Overhead Hold","3×20–35 s por braço.","8 min"],["Row + prehab","Row 3×8 + face pull 2×15 + rotação externa 2×15.","12 min"],["Core transmissor","Pallof 3×10 + ab wheel 3×8–12 + Copenhagen.","15 min"]];
if(p===2)return t==="force"?[["Força leve","Back squat 3×5 60–65% + pull-up 3×5 + RDL 2×6.","35–45 min"]]:t==="toss"?[["Toss Lab leve","Dip & Freeze + vertical jump + hang clean leve.","30–40 min"]]:[["Primer técnico","CMJ 3×2 + med ball 3×2 + push press leve 3×3.","25–35 min"]];
if(p===5)return t==="force"?[["Testes submáximos","Atualize e1RM de squat e weighted pull-up sem falha.","45 min"]]:t==="toss"?[["Teste de potência","CMJ + broad jump + vídeo lateral do dip-drive + hang clean.","40 min"]]:[["Primer / recuperação","Pliometria mínima + mobilidade + prehab.","25–30 min"]];
if(t==="force")return p===0?[["CMJ + Stick","4×3. Máxima intenção.","8 min"],["Back Squat","5×5. Brace e subida agressiva.","RPE 7–8"],["Weighted Pull-up","4×4–6.","10 min"],["RDL","3×6.","10 min"],["Bulgarian Split Squat","3×6/perna.","8 min"],["Farmer Carry + Ab Wheel","3×25 m + 3×8–12.","8 min"]]:p===1?[["CMJ","5×2.","8 min"],["Back Squat","5×3 pesado, sem grind.","RPE 8"],["Weighted Pull-up","5×3–5.","10 min"],["RDL","4×5.","10 min"],["Split Squat","3×5/perna.","8 min"]]:[["CMJ","4×2 máximo.","7 min"],["Back Squat","4×3 forte.","RPE 8"],["Weighted Pull-up","5×3.","9 min"],["RDL","3×5.","9 min"],["Split Squat","3×5/perna.","8 min"]];
if(t==="toss"){let b=[["Dip & Freeze","3–4×3. Costelas sobre pelve; dip vertical.","6 min"],["Vertical Jump + Arms","4×3. Pernas iniciam; braços terminam.","7 min"]];return p===0?[...b,["Jump Shrug","3×3. Tripla extensão para CIMA.","6 min"],["Hang Power Clean","5×3. Velocidade > carga.","15 min"],["Power Jerk","4×3. Dip vertical → drive → lockout.","12 min"],["Strict Press + Row","4×5 + 3×6–8.","12 min"]]:p===1?[...b,["Hang High Pull","4×3.","8 min"],["Hang Power Clean","6×2 rápido.","15 min"],["Power Jerk","5×2–3.","12 min"],["Dips com peso","3×5–8.","7 min"]]:[...b,["Hang Power Clean","5×2 rápido.","12 min"],["Clean + Power Jerk","4×(1+2).","12 min"],["Loaded Jump","4×3 leve/explosivo.","8 min"],["Push Press","4×3.","9 min"]]}
if(t==="speed")return p===0?[["Depth Jump Freeze","3×3.","7 min"],["Med Ball Overhead Throw","5×3 máximo/vertical.","8 min"],["Push Press","5×3 rápido.","12 min"],["Pogo Jump","3×10.","5 min"],["Core + Prehab","Pallof + Copenhagen + manguito.","15 min"]]:[["Depth Jump → Vertical","4×2.","8 min"],["Med Ball Throw","5×3.","7 min"],["Push Press","6×2 rápido.","12 min"],["Overhead Hold","3×25–35 s.","8 min"],["Core / Prehab","12 min.","12 min"]];return[]}
let picked=null;function move(from,to,t){S.schedule[from]=(S.schedule[from]||[]).filter(x=>x!==t);S.schedule[to]=S.schedule[to]||[];if(!S.schedule[to].includes(t))S.schedule[to].push(t);picked=null;save();render()}
function renderCal(){let ds=dates();seed(ds);let c=document.querySelector("#calendar");c.innerHTML="";let labs=["SEG","TER","QUA","QUI","SEX","SÁB","DOM"];document.querySelector("#range").textContent=ds[0].toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})+" — "+ds[6].toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});
ds.forEach((d,i)=>{let k=iso(d),el=document.createElement("div");el.className="day"+(k===iso(new Date())?" today":"");el.innerHTML=`<div class="dayname">${labs[i]}</div><div class="daynum">${d.getDate()}</div><div class="items"></div>`;let box=el.querySelector(".items"),arr=S.schedule[k]||[];if(!arr.length)box.innerHTML='<div class="empty">Solte aqui</div>';arr.forEach(t=>{let x=document.createElement("div");x.className=`card ${t}`;x.draggable=true;x.innerHTML=`${N[t]}<small>${DESC[t]}</small>`;x.ondragstart=e=>e.dataTransfer.setData("text/plain",JSON.stringify({from:k,t}));x.onclick=e=>{e.stopPropagation();document.querySelectorAll(".card").forEach(y=>y.style.outline="");picked={from:k,t};x.style.outline="2px solid white"};box.appendChild(x)});el.ondragover=e=>{e.preventDefault();el.classList.add("target")};el.ondragleave=()=>el.classList.remove("target");el.ondrop=e=>{e.preventDefault();el.classList.remove("target");try{let x=JSON.parse(e.dataTransfer.getData("text/plain"));move(x.from,k,x.t)}catch{}};el.onclick=()=>{if(picked)move(picked.from,k,picked.t)};c.appendChild(el)})}
function renderToday(){let p=pi(S.week),arr=S.schedule[iso(new Date())]||[],t=arr.find(x=>x!=="recovery")||arr[0],d=todayData(),bs=t?workout(t):[];document.querySelector("#phaseBadge").textContent=`${PH[p][0]} • S${S.week}`;document.querySelector("#date").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});document.querySelector("#todayTitle").textContent=t?N[t]:"Dia livre";document.querySelector("#todayMeta").textContent=t?`${PH[p][0]} • ${DESC[t]}`:PH[p][1];document.querySelector("#sessionTitle").textContent=t?N[t]:"Sem treino agendado";document.querySelector("#cue").innerHTML=(t==="toss"||t==="speed")?'<div class="cue"><b>EMPURRA O CHÃO E CRESCE.</b><span>DOWN → UP • costelas sobre pelve • sem projetar quadril/barriga à frente.</span></div>':"";let w=document.querySelector("#workout");w.innerHTML="";bs.forEach((b,i)=>{let ok=d.done.includes(i),x=document.createElement("div");x.className="block";x.innerHTML=`<button class="check ${ok?"done":""}" data-i="${i}">${ok?"✓":"○"}</button><div><h3>${b[0]}</h3><p>${b[1]}</p><p class="meta">${b[2]}</p></div>`;w.appendChild(x)});if(!bs.length)w.innerHTML='<div class="empty">Arraste um treino para hoje.</div>';w.querySelectorAll(".check").forEach(x=>x.onclick=()=>{let i=+x.dataset.i;d.done=d.done.includes(i)?d.done.filter(n=>n!==i):[...d.done,i];save();renderToday()});let pct=bs.length?Math.round(d.done.length/bs.length*100):0;document.querySelector("#pct").textContent=pct+"%";document.querySelector("#ring").style.background=`conic-gradient(#ff3446 ${pct}%,#293142 ${pct}%)`;document.querySelector("#weekInput").value=S.week;document.querySelector("#phaseInput").value=PH[p][0];document.querySelector("#focus").textContent=PH[p][1];let sc=S.scores[iso(new Date())]||{};["height","vertical","timing","extension","control"].forEach(k=>document.querySelector("#"+k).value=sc[k]||"");document.querySelector("#score").textContent=["height","vertical","timing","extension","control"].reduce((a,k)=>a+(+sc[k]||0),0)+"/25"}
function render(){renderCal();renderToday()}document.querySelector("#prev").onclick=()=>{S.offset--;save();renderCal()};document.querySelector("#next").onclick=()=>{S.offset++;save();renderCal()};document.querySelector("#clear").onclick=()=>{todayData().done=[];save();renderToday()};document.querySelector("#saveWeek").onclick=()=>{S.week=Math.max(1,Math.min(16,+document.querySelector("#weekInput").value||1));save();render()};document.querySelector("#saveScore").onclick=()=>{let s={};["height","vertical","timing","extension","control"].forEach(k=>s[k]=+document.querySelector("#"+k).value||0);S.scores[iso(new Date())]=s;save();renderToday();alert("Toss Score salvo.")};render();